In [87]:
import numpy as np
import pandas as pd

In [88]:
df = pd.DataFrame([
    [8 , 8 , 4], 
    [7 , 9 , 5],
    [6 , 10 , 6],
    [5, 12, 7]
], columns= ['cgpa', 'Profile_Score', 'LPA'])

In [89]:
df

cgpa  Profile_Score  LPA
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [90]:
def initialize_paramters(layers_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layers_dims)

    for l in range(1, L):
        parameters['W' + str(l)] = np.ones((layers_dims[l-1], layers_dims[l])) * 0.1
        parameters['b' + str(l)] = np.zeros((layers_dims[l], 1))

    return parameters

In [91]:
initialize_paramters([2, 2, 1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [92]:
def linear_forward(A_prev, W, b):
    Z = np.dot(W.T, A_prev) + b

    return Z

Forward Propagation

In [112]:
def L_layer_forward(X, parameters):
    A = X
    L = len(parameters) // 2

    for l in range(1, L+1):
        A_prev = A
        W1 = parameters['W' + str(l)]
        b1 = parameters['b' + str(l)]

        #print("A" + str(l-1) + " : " , A_prev)
        #print("W" + str(l) + " : " , W1)
        #print("b" + str(l) + " : " , b1)
        #print("--" * 20)

        A = linear_forward(A_prev , W1 , b1)
        #print("A" + str(l) + " : ", A)
        #print("**"*20)

    return A, A_prev

In [94]:
X = df[['cgpa', 'Profile_Score']].values[0].reshape(2, 1)
y = df[['LPA']].values[0][0]
print(X, "\n", y)

[[8]
 [8]] 
 4


Parameter Initialization

In [95]:
parameters = initialize_paramters([2 , 2 , 1])

In [96]:
y_hat, A1 = L_layer_forward(X, parameters)

A0 :  [[8]
 [8]]
W1 :  [[0.1 0.1]
 [0.1 0.1]]
b1 :  [[0.]
 [0.]]
----------------------------------------
A1 :  [[1.6]
 [1.6]]
****************************************
A1 :  [[1.6]
 [1.6]]
W2 :  [[0.1]
 [0.1]]
b2 :  [[0.]]
----------------------------------------
A2 :  [[0.32]]
****************************************


Calculating loss 

Mean Squared Error

In [97]:
y_hat = y_hat[0][0]

In [98]:
A1

array([[1.6],
       [1.6]])

In [99]:
def update_parameters(parameters, y , y_hat, A1, X):
    parameters['W2'][0][0] = parameters['W2'][0][0] + 0.001 * 2 * (y - y_hat) * A1[0][0]
    parameters['W2'][1][0] = parameters['W2'][1][0] + 0.001 * 2 * (y - y_hat) * A1[1][0]
    parameters['b2'][0][0] = parameters['W2'][0][0] + 0.001 * 2 * (y - y_hat)

    parameters['W1'][0][0] = parameters['W1'][0][0] + 0.001 * 2 * (y - y_hat) * parameters['W2'][0][0] * X[0][0]
    parameters['W1'][0][1] = parameters['W1'][0][1] + 0.001 * 2 * (y - y_hat) * parameters['W2'][0][0] * X[1][0]
    parameters['b1'][0][0] = parameters['b1'][0][0] + 0.001 * 2 * (y - y_hat) * parameters['W2'][0][0]

    parameters['W1'][1][0] = parameters['W1'][1][0] + 0.001 * 2 * (y - y_hat) * parameters['W2'][1][0] * X[0][0]
    parameters['W1'][1][1] = parameters['W1'][1][1] + 0.001 * 2 * (y - y_hat) * parameters['W2'][1][0] * X[1][0]
    parameters['b1'][1][0] = parameters['b1'][1][0] + 0.001 * 2 * (y - y_hat) * parameters['W2'][1][0]

In [100]:
update_parameters(parameters, y , y_hat, A1, X)

In [101]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

-----------------------------------------------------------------------------------------------------

Now doing the same process for 2nd student

In [102]:
X = df[['cgpa', 'Profile_Score']].values[1].reshape(2, 1)
y = df[['LPA']].values[1][0]
print(X, "\n", y)

[[7]
 [9]] 
 5


In [105]:
y_hat, A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

A0 :  [[7]
 [9]]
W1 :  [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1 :  [[0.00082267]
 [0.00082267]]
----------------------------------------
A1 :  [[1.70612461]
 [1.70612461]]
****************************************
A1 :  [[1.70612461]
 [1.70612461]]
W2 :  [[0.111776]
 [0.111776]]
b2 :  [[0.119136]]
----------------------------------------
A2 :  [[0.50054357]]
****************************************


In [107]:
update_parameters(parameters, y , y_hat, A1, X)
parameters

{'W1': array([[0.12356486, 0.12841729],
        [0.12356486, 0.12841729]]),
 'b1': array([[0.00324888],
        [0.00324888]]),
 'W2': array([[0.14248253],
        [0.14248253]]),
 'b2': array([[0.15148145]])}

----------------------------------------------------------------------------------------
3rd student

In [109]:
X = df[['cgpa', 'Profile_Score']].values[2].reshape(2, 1)
y = df[['LPA']].values[2][0]
print(X, "\n", y)

print("\n")

y_hat, A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

print("\n")

update_parameters(parameters, y , y_hat, A1, X)
print(parameters)

[[ 6]
 [10]] 
 6


A0 :  [[ 6]
 [10]]
W1 :  [[0.13390237 0.14564646]
 [0.13395418 0.14573282]]
b1 :  [[0.0049718 ]
 [0.00498044]]
----------------------------------------
A1 :  [[2.14792781]
 [2.3361874 ]]
****************************************
A1 :  [[2.14792781]
 [2.3361874 ]]
W2 :  [[0.16336721]
 [0.16418601]]
b2 :  [[0.17391349]]
----------------------------------------
A2 :  [[0.90838374]]
****************************************


{'W1': array([[0.14522042, 0.16450989],
       [0.1454394 , 0.16487485]]), 'b1': array([[0.00685814],
       [0.00689464]]), 'W2': array([[0.18524005],
       [0.18797595]]), 'b2': array([[0.19542329]])}


In [110]:
X = df[['cgpa', 'Profile_Score']].values[3].reshape(2, 1)
y = df[['LPA']].values[3][0]
print(X, "\n", y)

print("\n")

y_hat, A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

print("\n")

update_parameters(parameters, y , y_hat, A1, X)
print(parameters)

[[ 5]
 [12]] 
 7


A0 :  [[ 5]
 [12]]
W1 :  [[0.14522042 0.16450989]
 [0.1454394  0.16487485]]
b1 :  [[0.00685814]
 [0.00689464]]
----------------------------------------
A1 :  [[2.47823302]
 [2.80794223]]
****************************************
A1 :  [[2.47823302]
 [2.80794223]]
W2 :  [[0.18524005]
 [0.18797595]]
b2 :  [[0.19542329]]
----------------------------------------
A2 :  [[1.18231691]]
****************************************


{'W1': array([[0.15767464, 0.19440001],
       [0.15827596, 0.1956826 ]]), 'b1': array([[0.00934899],
       [0.00946195]]), 'W2': array([[0.2140752 ],
       [0.22064738]]), 'b2': array([[0.22571057]])}


---------------------------------------------------------------------------------------------------------
### Epoch Implementation

In [113]:
parameters = initialize_paramters([2 , 2 , 1])
epochs = 5

for i in range(epochs):
    Loss = []
    for j in range(df.shape[0]):
        X = df[['cgpa', 'Profile_Score']].values[j].reshape(2, 1)
        y = df[['LPA']].values[j][0]

        y_hat, A1 = L_layer_forward(X, parameters)
        y_hat = y_hat[0][0]

        Loss.append((y - y_hat) ** 2)

        update_parameters(parameters, y , y_hat, A1, X)

    print(f"Epoch {i+1} Loss: {np.mean(Loss)}")

parameters

Epoch 1 Loss: 25.32296784649163
Epoch 2 Loss: 18.375520362681193
Epoch 3 Loss: 9.589003823501418
Epoch 4 Loss: 3.321122941584228
Epoch 5 Loss: 1.3512635453804291


{'W1': array([[0.26640448, 0.38768705],
        [0.2795525 , 0.41227214]]),
 'b1': array([[0.02770069],
        [0.02999019]]),
 'W2': array([[0.41385806],
        [0.48606825]]),
 'b2': array([[0.41730944]])}